//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puzzles {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs_2021 {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs_2021() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Puzzles.Inputs_2021", typeof(Inputs_2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 157
        ///158
        ///167
        ///157
        ///148
        ///154
        ///155
        ///156
        ///151
        ///126
        ///125
        ///119
        ///128
        ///136
        ///135
        ///144
        ///159
        ///157
        ///164
        ///163
        ///165
        ///166
        ///163
        ///186
        ///194
        ///197
        ///188
        ///203
        ///225
        ///228
        ///248
        ///263
        ///253
        ///280
        ///279
        ///277
        ///281
        ///282
        ///286
        ///290
        ///292
        ///275
        ///274
        ///282
        ///293
        ///301
        ///307
        ///305
        ///300
        ///296
        ///301
        ///310
        ///302
        ///299
        ///300
        ///308
        ///306
        ///327
        ///329
        ///323
        ///320
        ///324
        ///327
        ///340
        ///336
        ///343
        ///344
        ///345
        ///346
        ///347
        ///365
        ///368
        ///372
        ///373
        ///372
        ///371
        ///380
        ///379
        ///357
        ///380
        ///382
        ///392
        ///400
        ///375
        ///376
        ///374
        ///373
        ///376
        ///394
        ///407
        ///408
        ///406
        ///407
        ///405
        ///406
        ///405
        ///415
        ///399
        ///409
        ///405
        ///406
        ///416
        ///42 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_01 {
            get {
                return ResourceManager.GetString("Rainer_01", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to forward 3
        ///down 9
        ///forward 5
        ///up 1
        ///forward 2
        ///down 1
        ///down 7
        ///down 5
        ///up 6
        ///forward 3
        ///down 6
        ///forward 9
        ///down 6
        ///forward 2
        ///down 4
        ///forward 4
        ///down 9
        ///down 7
        ///down 2
        ///down 4
        ///forward 3
        ///forward 6
        ///down 3
        ///up 1
        ///down 5
        ///down 8
        ///down 1
        ///forward 9
        ///forward 4
        ///forward 3
        ///down 3
        ///down 6
        ///down 3
        ///up 2
        ///down 3
        ///down 9
        ///down 1
        ///down 9
        ///up 8
        ///down 1
        ///down 9
        ///forward 9
        ///forward 2
        ///down 1
        ///forward 2
        ///down 9
        ///forward 9
        ///up 7
        ///forward 1
        ///up 8
        ///forward 7
        ///forward 6
        ///forward 2
        ///down 8
        ///forward 7
        ///down 3
        ///down 2
        ///down 1        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_02 {
            get {
                return ResourceManager.GetString("Rainer_02", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 011010010110
        ///101110100110
        ///011011011110
        ///100011010001
        ///011011100111
        ///011000100101
        ///101101011001
        ///010001001001
        ///100010110111
        ///001110110101
        ///100111011001
        ///100110111011
        ///000000111101
        ///000000011101
        ///011101000011
        ///101101001111
        ///110101011101
        ///010100000100
        ///100111010001
        ///111110001000
        ///000110110110
        ///001001101101
        ///001110110111
        ///101110110101
        ///010001111000
        ///111101010111
        ///110011101110
        ///010111011100
        ///100101011111
        ///111011011011
        ///100110100111
        ///001000101010
        ///101000010000
        ///101010000111
        ///000100100101
        ///111111111101
        ///00010010 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_03 {
            get {
                return ResourceManager.GetString("Rainer_03", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4,75,74,31,76,79,27,19,69,46,98,59,83,23,90,52,87,6,11,92,80,51,43,5,94,17,15,67,25,30,48,47,62,71,85,58,60,1,72,99,3,35,42,10,96,49,37,36,8,44,70,40,45,39,0,63,2,78,68,53,50,77,20,55,38,86,54,93,26,88,12,91,95,34,9,14,33,66,41,13,28,57,29,73,56,22,89,21,64,61,32,65,97,84,18,82,81,7,16,24
        ///
        ///30 46 94 20  2
        ///53 67 69 75 65
        ///27 24 85 28 60
        ///57 58 42 36 78
        ///35 98 87 91 93
        ///
        ///72 71 91 73 19
        /// 2 13 14  8 74
        ///42 34 31 56  9
        ///82 59 44 67 79
        ///49  6 98 10 30
        ///
        ///95 24 25 11 34
        ///57 65 41 92  8
        ///91 26  1 62 38
        ///47 93   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_04 {
            get {
                return ResourceManager.GetString("Rainer_04", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 102,578 -&gt; 363,317
        ///536,470 -&gt; 536,863
        ///578,460 -&gt; 203,835
        ///42,859 -&gt; 247,859
        ///618,147 -&gt; 147,618
        ///119,317 -&gt; 119,22
        ///14,975 -&gt; 950,39
        ///245,359 -&gt; 245,877
        ///835,278 -&gt; 159,954
        ///663,103 -&gt; 558,103
        ///194,85 -&gt; 194,193
        ///77,529 -&gt; 77,208
        ///677,459 -&gt; 515,459
        ///867,775 -&gt; 867,482
        ///674,508 -&gt; 191,508
        ///926,528 -&gt; 614,528
        ///816,467 -&gt; 816,765
        ///963,609 -&gt; 963,537
        ///838,400 -&gt; 915,400
        ///53,546 -&gt; 297,546
        ///745,938 -&gt; 396,589
        ///820,30 -&gt; 820,114
        ///351,406 -&gt; 351,212
        ///356,309 -&gt; 356,533
        ///592,221 -&gt; 179,634
        ///87,151 -&gt; 412,151
        ///35 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_05 {
            get {
                return ResourceManager.GetString("Rainer_05", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 3,5,4,1,2,1,5,5,1,1,1,1,4,1,4,5,4,5,1,3,1,1,1,4,1,1,3,1,1,5,3,1,1,3,1,3,1,1,1,4,1,2,5,3,1,4,2,3,1,1,2,1,1,1,4,1,1,1,1,2,1,1,1,3,1,1,4,1,4,1,5,1,4,2,1,1,5,4,4,4,1,4,1,1,1,1,3,1,5,1,4,5,3,1,4,1,5,2,2,5,1,3,2,2,5,4,2,3,4,1,2,1,1,2,1,1,5,4,1,1,1,1,3,1,5,4,1,5,1,1,4,3,4,3,1,5,1,1,2,1,1,5,3,1,1,1,1,1,5,1,1,1,1,1,1,1,2,2,5,5,1,2,1,2,1,1,5,1,3,1,5,2,1,4,1,5,3,1,1,1,2,1,3,1,4,4,1,1,5,1,1,4,1,4,2,3,5,2,5,1,3,1,2,1,4,1,1,1,1,2,1,4,1,3,4,1,1,1,1,1,1,1,2,1,5,1,1,1,1,2,3,1,1,2,3,1,1,3,1,1,3,1,3,1,3,3,1,1,2,1,3,2,3,1,1,3, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_06 {
            get {
                return ResourceManager.GetString("Rainer_06", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,106,684,36,657,427,156,197,56,205,1104,170,307,291,88,330,12,24,1128,440,1099,1523,936,198,266,1257,874,196,912,335,46,320,666,132,1035,145,877,1484,222,690,479,386,59,101,765,506,27,250,478,609,807,1566,317,138,1390,245,1178,211,64,714,510,256,430,371,182,464,398,1749,57,1023,4,891,1177,45 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_07 {
            get {
                return ResourceManager.GetString("Rainer_07", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to dcbgefa cebd bfega eadbf db cdfaeb dba bfcgda egadcf aedcf | egadcfb eafcd db debc
        ///dfea ea abe dfgaeb fdcgba badeg dcfbeag dbgaf bcged fcebag | gfadb dfagb fdgabe eagdbf
        ///cd gfcde cdbfage cbdfae edc fedgac gadc feagd febdga gbfec | adbfeg dbfcae facbde gcfde
        ///ecafb abgfc deacbgf fe fbe fgec edgafb cgbafd ebfgca ebcad | cfbae fbcga dfabceg ceabf
        ///eagfcd abfdecg fe fdae egf cfgda gcedb dcgabf bcegaf cegdf | gcfda feg efg cadgbf
        ///gfcdab efadc cadbgfe beca badfce ecfbd edcagf gbdef cfb bc | gdecbfa cbea gedbf  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_08 {
            get {
                return ResourceManager.GetString("Rainer_08", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 0198765456793498765667899895432323459895457899886789876798656767890198989323997654321296543219876545
        ///9997654345689987654345998789591014598784345798765678965987543459921987978919876543210989694998765432
        ///7898543254568998875657895679989125987653236989654567934597654567899876869899989874349978989899654321
        ///6987654123457899986767894578978939876543125878943478945698875998954945756789999965498769876789965432
        ///5698743016568996799878923489467894985432014567896567896789989899893234545678999876987658765679896545
        ///49 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_09 {
            get {
                return ResourceManager.GetString("Rainer_09", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt;{&lt;[&lt;&lt;&lt;{&lt;&lt;(&lt;({}())({}[]))[[{}[]]&lt;{}[]&gt;])[&lt;[{}[]]{()()}&gt;{((){})&lt;&lt;&gt;&lt;&gt;&gt;}]&gt;&gt;[&lt;(&lt;&lt;{}&gt;&gt;[&lt;()()&gt;&lt;&lt;&gt;&lt;&gt;&gt;]
        ///{[[[{&lt;[(([[{(({}))([&lt;&gt;[]]((){}))}&lt;&lt;&lt;[][]&gt;[{}{}]&gt;[{()[]}(()())]&gt;][[[{&lt;&gt;()}[{}[]]]]]]&lt;{{{{()[]}}}[[{[][]}{{
        ///([((&lt;(&lt;(&lt;&lt;([{{[][]}([]&lt;&gt;)}({&lt;&gt;{}}[[]()])]&lt;[[()()](()[])]([[][]](&lt;&gt;&lt;&gt;))&gt;&gt;{{&lt;(&lt;&gt;&lt;&gt;)[&lt;&gt;()]&gt;([[]()])}&lt;&lt;[[]()]&lt;[][
        ///{{{([((([({[{{()()}{&lt;&gt;[]}}({{}{}}([]{}))]{([{}&lt;&gt;])&lt;(&lt;&gt;&lt;&gt;){[]&lt;&gt;}}}})({{{(()())[[][]]}{&lt;{}{}&gt;
        ///{{([[((({(({({&lt;&gt;&lt;&gt;}([]{}))([()()]{[]{}})}[[({}{})&lt;(){}&gt;]&lt;&lt;()&lt;&gt;&gt;&gt;]){[[[()()][&lt;&gt;[]]}&lt;[{}()]{{}&lt;&gt;}
        ///{([&lt;[[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_10 {
            get {
                return ResourceManager.GetString("Rainer_10", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 4781623888
        ///1784156114
        ///3265645122
        ///4371551414
        ///3377154886
        ///7882314455
        ///6421348681
        ///7175424287
        ///5488242184
        ///2448568261
        ///.
        /// </summary>
        internal static string Rainer_11 {
            get {
                return ResourceManager.GetString("Rainer_11", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to he-JK
        ///wy-KY
        ///pc-XC
        ///vt-wy
        ///LJ-vt
        ///wy-end
        ///wy-JK
        ///end-LJ
        ///start-he
        ///JK-end
        ///pc-wy
        ///LJ-pc
        ///at-pc
        ///xf-XC
        ///XC-he
        ///pc-JK
        ///vt-XC
        ///at-he
        ///pc-he
        ///start-at
        ///start-XC
        ///at-LJ
        ///vt-JK
        ///.
        /// </summary>
        internal static string Rainer_12 {
            get {
                return ResourceManager.GetString("Rainer_12", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 17,52
        ///740,52
        ///559,424
        ///820,415
        ///880,718
        ///867,814
        ///1136,658
        ///420,170
        ///492,530
        ///300,686
        ///1201,233
        ///1161,116
        ///247,584
        ///43,754
        ///231,857
        ///980,388
        ///80,173
        ///560,478
        ///1148,4
        ///1121,187
        ///492,219
        ///649,492
        ///599,788
        ///624,456
        ///455,584
        ///52,277
        ///903,310
        ///177,598
        ///654,891
        ///277,623
        ///180,80
        ///68,702
        ///751,555
        ///55,788
        ///175,16
        ///288,236
        ///17,842
        ///1215,122
        ///1309,131
        ///475,639
        ///1148,113
        ///475,670
        ///140,763
        ///251,767
        ///261,191
        ///177,84
        ///1068,724
        ///179,639
        ///671,444
        ///569,148
        ///1051,297
        ///1076,495
        ///763,452
        ///1,152
        ///475,224
        ///80,423
        ///837,128
        ///1033, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_13 {
            get {
                return ResourceManager.GetString("Rainer_13", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPSSSFCFOFVFNVPKBFVN
        ///
        ///NV -&gt; V
        ///CF -&gt; O
        ///BB -&gt; F
        ///SB -&gt; H
        ///KF -&gt; O
        ///SP -&gt; H
        ///CS -&gt; V
        ///VF -&gt; F
        ///PC -&gt; H
        ///PH -&gt; H
        ///SF -&gt; F
        ///CP -&gt; B
        ///BC -&gt; H
        ///PB -&gt; V
        ///KO -&gt; B
        ///CV -&gt; S
        ///ON -&gt; B
        ///PV -&gt; F
        ///OO -&gt; B
        ///VV -&gt; B
        ///NO -&gt; B
        ///SH -&gt; N
        ///FC -&gt; C
        ///VO -&gt; B
        ///NN -&gt; C
        ///HH -&gt; S
        ///CK -&gt; C
        ///PF -&gt; N
        ///SN -&gt; K
        ///OK -&gt; F
        ///FH -&gt; S
        ///BP -&gt; K
        ///HO -&gt; K
        ///FB -&gt; P
        ///HC -&gt; N
        ///FP -&gt; P
        ///NC -&gt; H
        ///PK -&gt; O
        ///BV -&gt; P
        ///HK -&gt; S
        ///PP -&gt; N
        ///VC -&gt; K
        ///CH -&gt; C
        ///KS -&gt; V
        ///KB -&gt; V
        ///FN -&gt; P
        ///BS -&gt; O
        ///PS -&gt; N
        ///NS -&gt; B
        ///PN -&gt; N
        ///NP -&gt; H
        ///CB -&gt; S
        ///SV -&gt; O
        ///OC -&gt; H
        ///BO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_14 {
            get {
                return ResourceManager.GetString("Rainer_14", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 8278572114793756191833561127452853426929615899116958969481427593944191389121411192127899512211639555
        ///2495171585122426519281919685613271991924121543192937558138395964783255375528718245475125436917188379
        ///7961821999883965642974131223415952226122149135757469151378271261942142914126999286296912626324385126
        ///6441179418166119485338911954311735412134219517651998824469721124695113922376591228278111534398748579
        ///8424516666869191815919915114592841194492325941357613456911196292486835511835219129622871119578589971
        ///49 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_15 {
            get {
                return ResourceManager.GetString("Rainer_15", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 005532447836402684AC7AB3801A800021F0961146B1007A1147C89440294D005C12D2A7BC992D3F4E50C72CDF29EECFD0ACD5CC016962099194002CE31C5D3005F401296CAF4B656A46B2DE5588015C913D8653A3A001B9C3C93D7AC672F4FF78C136532E6E0007FCDFA975A3004B002E69EC4FD2D32CDF3FFDDAF01C91FCA7B41700263818025A00B48DEF3DFB89D26C3281A200F4C5AF57582527BC1890042DE00B4B324DBA4FAFCE473EF7CC0802B59DA28580212B3BD99A78C8004EC300761DC128EE40086C4F8E50F0C01882D0FE29900A01C01C2C96F38FCBB3E18C96F38FCBB3E1BCC57E2AA0154EDEC45096712A64A2520C6401A9E80213D9856265 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_16 {
            get {
                return ResourceManager.GetString("Rainer_16", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to target area: x=244..303, y=-91..-54
        ///.
        /// </summary>
        internal static string Rainer_17 {
            get {
                return ResourceManager.GetString("Rainer_17", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to [[[[0,6],[8,7]],[2,3]],[3,[[6,5],[0,0]]]]
        ///[[2,[9,[4,9]]],[[[3,0],4],[2,[4,7]]]]
        ///[[[4,[5,2]],[1,[9,7]]],[[2,4],[[4,5],4]]]
        ///[[[[6,7],8],[[6,6],3]],[6,[7,[4,9]]]]
        ///[[[[5,4],[7,4]],[8,[2,3]]],[[[9,7],6],[2,[4,7]]]]
        ///[[[[2,4],[0,9]],6],[[[7,3],[5,9]],[0,[2,3]]]]
        ///[[6,[9,[2,4]]],[[3,0],[1,[0,0]]]]
        ///[[3,7],[3,[2,0]]]
        ///[[0,[2,[4,6]]],[8,9]]
        ///[[[7,5],[[3,8],5]],[[[9,8],[4,3]],[5,[1,4]]]]
        ///[[9,[[4,7],[7,1]]],[[7,[8,7]],[4,[2,6]]]]
        ///[[[0,4],9],[[[5,1],[3,2]],4]]
        ///[[[5,9],2],[8,[3,[2,4]]]]
        ///[[[[2,2],[9,2]],[0,7]],[[ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_18 {
            get {
                return ResourceManager.GetString("Rainer_18", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to --- scanner 0 ---
        ///712,493,-580
        ///-705,-746,944
        ///-468,-742,927
        ///-906,-760,-387
        ///523,612,505
        ///-973,425,-333
        ///361,-777,-655
        ///-172,-143,-8
        ///403,-606,-574
        ///-655,761,677
        ///-670,-738,898
        ///459,511,-563
        ///713,-623,478
        ///-605,714,848
        ///-18,-8,104
        ///510,641,739
        ///-991,515,-523
        ///556,559,577
        ///709,-678,647
        ///789,-632,517
        ///-976,-761,-391
        ///-966,491,-435
        ///-611,679,810
        ///383,-654,-565
        ///641,491,-564
        ///-790,-798,-400
        ///
        ///--- scanner 1 ---
        ///-286,612,-671
        ///550,-491,494
        ///-344,-303,619
        ///487,-410,518
        ///973,-373,-692
        ///110,31,-17
        ///662,607,-702        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_19 {
            get {
                return ResourceManager.GetString("Rainer_19", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ######.#..##..######.....#...#.#...#.######.#.#...#..#..#..###.#####.#.####...#.#.#...#.#.#...#####..###.....#.#.....#.#.#..###..#.#.#####..#.....####.##.##..#..##.#.##.##..##.#####.####.#.#....#...#...#...#.#########..#..#####..#.#.###....#.##.###...##.#..#....##.###...#..##.#..#...#.#.#####.####...#.##..##..#.#######...#..##.##.....#..#..#.###...###.######..##.#..##.######....#.##.##...###.##..#.#.#.#########....####.####.#.#...#.#.#..#.#.##.#...#.#..#######..###..##.#..####.###...#.#.#.##.#####.##.###.#. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_20 {
            get {
                return ResourceManager.GetString("Rainer_20", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Player 1 starting position: 7
        ///Player 2 starting position: 1
        ///.
        /// </summary>
        internal static string Rainer_21 {
            get {
                return ResourceManager.GetString("Rainer_21", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to on x=-45..7,y=-17..27,z=5..49
        ///on x=-47..6,y=-17..30,z=-24..26
        ///on x=-41..3,y=-7..39,z=-40..13
        ///on x=-7..37,y=-13..39,z=-8..42
        ///on x=-28..25,y=1..47,z=-30..16
        ///on x=-17..35,y=-41..8,z=-24..28
        ///on x=-12..40,y=-16..36,z=-9..38
        ///on x=-42..5,y=-43..5,z=-41..5
        ///on x=-41..8,y=-19..32,z=-5..48
        ///on x=-7..45,y=-48..-4,z=-36..18
        ///off x=-30..-17,y=-18..-5,z=14..31
        ///on x=-34..11,y=-2..43,z=-40..12
        ///off x=15..31,y=8..23,z=-25..-14
        ///on x=1..49,y=-7..39,z=-21..27
        ///off x=-10..0,y=24..33,z=-25..-8
        ///on x=-45..1,y=-5..45,z=-2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_22 {
            get {
                return ResourceManager.GetString("Rainer_22", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #############
        ///#...........#
        ///###B#C#A#D###
        ///  #B#C#D#A#
        ///  #########
        ///.
        /// </summary>
        internal static string Rainer_23 {
            get {
                return ResourceManager.GetString("Rainer_23", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to inp w
        ///mul x 0
        ///add x z
        ///mod x 26
        ///div z 1
        ///add x 12
        ///eql x w
        ///eql x 0
        ///mul y 0
        ///add y 25
        ///mul y x
        ///add y 1
        ///mul z y
        ///mul y 0
        ///add y w
        ///add y 1
        ///mul y x
        ///add z y
        ///inp w
        ///mul x 0
        ///add x z
        ///mod x 26
        ///div z 1
        ///add x 12
        ///eql x w
        ///eql x 0
        ///mul y 0
        ///add y 25
        ///mul y x
        ///add y 1
        ///mul z y
        ///mul y 0
        ///add y w
        ///add y 1
        ///mul y x
        ///add z y
        ///inp w
        ///mul x 0
        ///add x z
        ///mod x 26
        ///div z 1
        ///add x 15
        ///eql x w
        ///eql x 0
        ///mul y 0
        ///add y 25
        ///mul y x
        ///add y 1
        ///mul z y
        ///mul y 0
        ///add y w
        ///add y 16
        ///mul y x
        ///add z y
        ///inp w
        ///mul x 0
        ///add x  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_24 {
            get {
                return ResourceManager.GetString("Rainer_24", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &gt;...v&gt;..v......v&gt;&gt;&gt;.&gt;....&gt;v.&gt;v...&gt;....v...&gt;...&gt;.&gt;v.&gt;&gt;&gt;&gt;..&gt;.&gt;&gt;v.........&gt;&gt;vv..&gt;vvv&gt;.v&gt;v..v....v.&gt;.&gt;v&gt;...v&gt;.&gt;..&gt;vv.....v..&gt;v.v&gt;.v&gt;&gt;...v.v.&gt;&gt;.
        ///..&gt;&gt;&gt;....vv..&gt;&gt;.vv.v..v....&gt;v.&gt;&gt;.....&gt;.&gt;.&gt;v......v...v.........&gt;.&gt;&gt;..v.&gt;.....vvv..&gt;..vvv.&gt;.&gt;..&gt;v.vv&gt;...vv.v.v.&gt;.v..&gt;.v...v....&gt;&gt;vvv&gt;.v&gt;v&gt;&gt;v
        ///v&gt;...v.v.v.&gt;&gt;...vv&gt;vvv..vv...v...&gt;.v&gt;....&gt;&gt;.&gt;...&gt;.vv..&gt;&gt;.v&gt;v........&gt;v.v.&gt;v&gt;&gt;..&gt;.&gt;..........vvv.&gt;...v&gt;..v.&gt;&gt;&gt;..&gt;.v&gt;...&gt;..&gt;..&gt;v...&gt;v..v&gt;..&gt;.
        ///..v&gt;&gt;&gt;&gt;&gt;...v.v.vv&gt;.....&gt;....&gt;.vv.v&gt;&gt;...v....&gt;.v&gt;v&gt;...&gt;...&gt;.....&gt;&gt;v.&gt;&gt;.vvv.vvv..v&gt;&gt;..vv.&gt;v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rainer_25 {
            get {
                return ResourceManager.GetString("Rainer_25", resourceCulture);
            }
        }
    }
}
